### ISSUE TITLE
Wheel support

### ISSUE THREAD

**Issue by kevin-brown** [sendgrid/smtpapi-python#11]
http://pythonwheels.com/

Right now, only the `tar.gz` file is being distributed on PyPI for [smtpapi](https://pypi.python.org/pypi/smtpapi), which isn't _that much_ of an issue, but it does add some time to installing the package.

This package should be compatible with the Wheel format, considering it doesn't appear to have any C dependencies and it is compatible with both Python 2 and 3. As a result, you should only need to generate a universal wheel and then everyone (on all systems) will get the ability to install smtpapi with just the wheel, without having to do any extra work.

**Comment by thinkingserious** [comment]
Thanks for the suggestion @kevin-brown,

I've added this to our backlog for implementation.

**Comment by kevin-brown** [comment]
I'm curious if this was closed off because this will happen in the next release, or if it was closed off because there hasn't been any new comments?

**Comment by thinkingserious** [comment]
@kevin-brown,

Yes, this will happen in the next release. Thanks!
