### ISSUE TITLE
Add a Code Of Conduct

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/smtpapi-python#13]
Add a file to the root of this repo called CODE_OF_CONDUCT.md, with the content from the [same file in our docs repo](https://github.com/sendgrid/docs/pull/3048).

**Comment by PseudoAj** [comment]
Added code of conduct. Thanks for a quick and easy job. PR is here: https://github.com/sendgrid/smtpapi-python/pull/14

**Comment by mbernier** [comment]
Thank you!!
