### ISSUE TITLE
Fix "similar-code" issue in smtpapi/__init__.py

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/smtpapi-python#46]
Similar blocks of code found in 4 locations. Consider refactoring.

Check the issues mentioned here: 
https://codeclimate.com/github/sendgrid/smtpapi-python/smtpapi/__init__.py

**Comment by Bezzy1999** [comment]
Hi I'd like to work on this, should I just create a pr? Thanks.

**Comment by thinkingserious** [comment]
Hi @Bezzy1999,

Sorry for the super delayed response :(

It looks like @Tranquilled has already submitted a PR for this.

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/smtpapi-python/pull/53
