### ISSUE TITLE
Make smtpapi-python follow PEP8 standards

### ISSUE THREAD

**Issue by Madhur96** [sendgrid/smtpapi-python#49]
#### Issue Summary

Make this repo follow to PEP8 standard

**Comment by Madhur96** [comment]
I would like to work on this issue

**Comment by kushagra189** [comment]
I would like to work on YAML and Markdown

**Comment by parth-p** [comment]
i would like to work on YAML.

**Comment by vivek-7** [comment]
@Madhur96 Only you can work on markdown and YAML. No need of new PR.

**Comment by kushagra189** [comment]
are bhai bhai  bhai

**Comment by vivek-7** [comment]
@parth-p Arey Bhai Bhai Bhai

**Comment by kushagra189** [comment]
i would like to work on markdown
