### ISSUE TITLE
Create a Use Cases Directory

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/smtpapi-python#60]
Due to the success we have seen from hacktoberfest, we are seeing more people create use cases. This is amazing! 
We want to make sure that everyone can find them. Please help us to break up this file and make it easier to read and manage:
- Create a Use Cases Directory
- Put a README.md in this directory
- Make a file in the new directory for each individual Use Case from USE_CASES.md, copy the content to this file
- For each file you've created, link to it from the README you created
- Organize the links in the README by type
- Make sure the names of the files you created are related to the Use Case
Thank you!

**Comment by shorrock** [comment]
I'd like to take this!

**Comment by shorrock** [comment]
@thinkingserious two questions:

1: Where can I find the mentioned USE_CASES.md file? I don't see it in the master branch at this time.
2: Where should this Use Cases directory be created and what shall it be called? I'm presuming this should be located within the root directory and named along the lines of "use-cases".

**Comment by thinkingserious** [comment]
Hello @shorrock,

For an example USE_CASES.md file, please [see here](https://github.com/sendgrid/sendgrid-python/blob/master/USE_CASES.md).
