### ISSUE TITLE
Implement auto-deploy to package manager

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/smtpapi-python#67]
#### Issue Summary

When all tests on the master branch pass in Travis CI, we would like to auto-deploy the release to the package manager.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* when Travis CI passes all tests on the master branch we auto-deploy to the package manager
* the version is determined by the `CHANGELOG.md`

**Comment by rozig** [comment]
Hi @thinkingserious . We can set deploy option in .travis.yml. So it deploys the project automatically to the PyPi once it passes all the tests.

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/smtpapi-python/pull/101
