### ISSUE TITLE
"TypeError: Decimal(x) is not JSON serializable" on call to SMTPAPIHeader.json_string()

### ISSUE THREAD

**Issue by jstol** [sendgrid/smtpapi-python#7]
I'm trying to pass a `Decimal` object (https://docs.python.org/2/library/decimal.html#decimal.Decimal) as a message substitution value, but the call to `json.dumps(result)` in the `SMTPAPIHeader` class' `json_string()` method (see here: https://github.com/sendgrid/smtpapi-python/blob/master/smtpapi/__init__.py#L85) is causing a TypeError to be thrown with the message `TypeError: Decimal(x) is not JSON serializable` (where `x` is the decimal value, ex. `'3.14'`).

Would it be possible to switch over from the standard `json` module to `simplejson` (https://github.com/simplejson/simplejson)? The call to `json.dumps(result)` would remain the same, but would allow for the use of additional encoders that are provided by `simplejson`.

If not, is there another nice way of getting around this issue?

**Comment by thinkingserious** [comment]
Hi @jstol,

Have you tried this solution? http://stackoverflow.com/a/16957370

I'm hesitant to use a non-standard library if not necessary, but I'll await your feedback on the above "fix".

If I were to make that change, it would likely do it this way: http://stackoverflow.com/a/712799

Thanks!

**Comment by thinkingserious** [comment]
Hello @jstol, are you still experiencing this issue?

**Comment by jstol** [comment]
@thinkingserious the solution you mentioned (http://stackoverflow.com/a/16957370) would likely require that I modify the source code, unfortunately, as the call to `json.dumps` is within the `SMTPAPIHeader.json_string` method.

A potential solution which doesn't require `simplejson` as a dependency is to create a custom JSON encoder class which can encode the Decimal class (http://stackoverflow.com/a/3885198/1424734). This would also allow for support to be added later on for other common classes that aren't supported by `json` by default. I'll submit a PR with the proposed changes.

**Comment by thinkingserious** [comment]
Awesome, thanks for taking the time to submit a pull request! We'll take a look soon.

**Comment by thinkingserious** [comment]
Merging: https://github.com/sendgrid/smtpapi-python/pull/9

Thanks again for taking the time to implement this!

**Comment by jstol** [comment]
Thanks!

**Comment by tanvirstreame** [comment]
use str() to convert decimal to string
