### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by 42B** [sendgrid/smtpapi-python#89]
#### Issue Summary
Even the syntax highlighting here on GitHub (in red) shows this to be invalid syntax. Simply changing `||` to `or` should solve this problem. One other consideration could be to use [`self.assertTrue(...)`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertTrue) instead of `self.assertEqual(True, ...)` for the other tests in this file.

@mbernier -> b26031be27a36460758259e74b4b372a8b2ff07d

https://github.com/sendgrid/smtpapi-python/blob/97cca3460802d62d288c06353d4f687d3c0e7ed6/test/test_project.py#L12

https://github.com/sendgrid/smtpapi-python/blob/97cca3460802d62d288c06353d4f687d3c0e7ed6/test/test_project.py#L16

https://github.com/sendgrid/smtpapi-python/blob/97cca3460802d62d288c06353d4f687d3c0e7ed6/test/test_project.py#L52

#### Steps to Reproduce

```python
$ python2
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.isdir("./Dockerfile") || os.path.isdir("./docker/Dockerfile")
  File "<stdin>", line 1
    os.path.isdir("./Dockerfile") || os.path.isdir("./docker/Dockerfile")
                                   ^
SyntaxError: invalid syntax

$ python
Python 3.7.1 (default, Oct 20 2018, 18:18:46) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> os.path.isdir("./Dockerfile") || os.path.isdir("./docker/Dockerfile")
  File "<stdin>", line 1
    os.path.isdir("./Dockerfile") || os.path.isdir("./docker/Dockerfile")
                                   ^
SyntaxError: invalid syntax

```

**Comment by hugovk** [comment]
Here's a PR: https://github.com/sendgrid/smtpapi-python/pull/90.

**Comment by 42B** [comment]
@hugovk 

Any reason why you didn't convert to using `assertTrue`'s instead?

**Comment by hugovk** [comment]
Because I didn't read your comment in full :) That makes much more sense, I've updated the PR. Thanks!
