### ISSUE TITLE
Python version badge reflects missing status in README.rst

### ISSUE THREAD

**Issue by dhruvhacks** [sendgrid/smtpapi-python#97]
#### Issue Summary
It seems smtpapi is not configured properly at [pypi.org](https://pypi.org/project/smtpapi/). Complete smtpapi-python description and python versions are missing.

#### Current status
[![PyPI pyversions](https://img.shields.io/pypi/pyversions/smtpapi.svg)](https://pypi.python.org/pypi/amtpapi/)

For now, this badge should be removed since README.rst includes the python versions under ```Installation Prerequisites``` [line 34](https://raw.githubusercontent.com/sendgrid/smtpapi-python/master/README.rst)

**Comment by childish-sambino** [comment]
Should be fixed by https://github.com/sendgrid/smtpapi-python/commit/b3e29d5b5cf918b5281dc6b8c91bbe2d3ca73209 on the next release.
